# Generated by Django 5.1.1 on 2024-11-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='calories',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='carbohydrates',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='fats',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='proteins',
            field=models.FloatField(),
        ),
    ]
