# Generated by Django 5.1.1 on 2024-11-14 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_savedfooditem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.URLField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeFoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.FloatField()),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_food_items', to='nutrition.fooditem')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_food_items', to='nutrition.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='food_items',
            field=models.ManyToManyField(related_name='recipes', through='nutrition.RecipeFoodItem', to='nutrition.fooditem'),
        ),
        migrations.AddConstraint(
            model_name='recipefooditem',
            constraint=models.UniqueConstraint(fields=('recipe', 'food_item'), name='unique_food_in_recipe'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('name', 'creator'), name='unique_recipe_per_creator'),
        ),
    ]
