# Generated by Django 5.1.1 on 2024-11-18 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_savedrecipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipefooditem',
            old_name='grams',
            new_name='quantity',
        ),
    ]
