# Generated by Django 5.1.1 on 2024-11-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0007_rename_photo_recipe_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.URLField(blank=True, default='https://firebasestorage.googleapis.com/v0/b/eatnlift-d2f8e.firebasestorage.app/o/uploads%2Frecipes%2Frecipe-default-image.png?alt=media&token=d8274913-c9a8-47a8-b4c5-9791190e774f'),
        ),
    ]
