# Generated by Django 5.1.1 on 2024-11-22 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0010_alter_recipienutritionalplan_meal_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('ESMORZAR', 'Breakfast'), ('DINAR', 'Lunch'), ('BERENAR', 'Snack'), ('SOPAR', 'Dinner')], max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'meal_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FoodItemMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_food_items', to='nutrition.fooditem')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='nutrition.meal')),
            ],
            options={
                'unique_together': {('meal', 'food_item')},
            },
        ),
    ]
