# Generated by Django 5.1.1 on 2024-11-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0011_meal_fooditemmeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditemmeal',
            name='quantity',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
