# Generated by Django 5.1.1 on 2024-11-26 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0013_check'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Check',
        ),
    ]
