# Generated by Django 5.1.1 on 2024-12-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_savedworkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='picture',
            field=models.URLField(blank=True, default='https://firebasestorage.googleapis.com/v0/b/eatnlift-d2f8e.firebasestorage.app/o/uploads%2Fexercises%2Fdefault_exercise.png?alt=media&token=22eed71d-9497-4e51-98af-ce46845b0615'),
        ),
    ]
