# Generated by Django 5.1.1 on 2024-12-10 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_alter_exercise_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='picture',
            field=models.URLField(blank=True, default='https://firebasestorage.googleapis.com/v0/b/eatnlift-d2f8e.firebasestorage.app/o/uploads%2Fexercises%2Fdefault_exercise.png?alt=media&token=22eed71d-9497-4e51-98af-ce46845b0615'),
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseInRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('DILLUNS', 'Dilluns'), ('DIMARTS', 'Dimarts'), ('DIMECRES', 'Dimecres'), ('DIJOUS', 'Dijous'), ('DIVENDRES', 'Divendres'), ('DISSABTE', 'Dissabte'), ('DIUMENGE', 'Diumenge')], max_length=20)),
                ('sets', models.PositiveIntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_routines', to='training.exercise')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises_in_routine', to='training.routine')),
            ],
            options={
                'unique_together': {('routine', 'week_day', 'exercise')},
            },
        ),
    ]
