# Generated by Django 5.1.1 on 2024-12-11 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_alter_exercise_picture_routine_exerciseinroutine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseinroutine',
            name='sets',
        ),
    ]
