# Generated by Django 5.1.1 on 2024-10-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activity',
            field=models.CharField(choices=[('Sedentarisme', 'Sedentary'), ('Activitat lleugera', 'Light Activity'), ('Activitat moderada', 'Moderate Activity'), ('Activitat intensa', 'Intense Activity'), ('Activitat molt intensa', 'Very Intense Activity')], max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='goal',
            field=models.CharField(choices=[('Guanyar múscul', 'Gain Muscle'), ('Perdre greix', 'Lose Fat'), ('Mantenir el pes', 'Maintain Weight')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
