# Generated by Django 5.1.1 on 2024-10-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_activity_customuser_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='genre',
            field=models.CharField(choices=[('Masculí', 'Male'), ('Femení', 'Female')], max_length=7, null=True),
        ),
    ]
