# Generated by Django 5.1.1 on 2024-10-30 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('genre', models.CharField(choices=[('Masculí', 'Male'), ('Femení', 'Female')], max_length=7, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('goal', models.CharField(choices=[('Guanyar múscul', 'Gain Muscle'), ('Perdre greix', 'Lose Fat'), ('Mantenir el pes', 'Maintain Weight')], max_length=15, null=True)),
                ('activity', models.CharField(choices=[('Sedentarisme', 'Sedentary'), ('Activitat lleugera', 'Light Activity'), ('Activitat moderada', 'Moderate Activity'), ('Activitat intensa', 'Intense Activity'), ('Activitat molt intensa', 'Very Intense Activity')], max_length=22, null=True)),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
                ('proteins', models.PositiveIntegerField(blank=True, null=True)),
                ('fats', models.PositiveIntegerField(blank=True, null=True)),
                ('carbohydrates', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='height',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='weight',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
    ]
