# Generated by Django 5.1.1 on 2024-11-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.URLField(blank=True, default='gs://eatnlift-d2f8e.firebasestorage.app/uploads/user_profile/default_user.png'),
        ),
    ]
