# Generated by Django 5.1.1 on 2024-11-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_passwordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.URLField(blank=True, default='https://firebasestorage.googleapis.com/v0/b/eatnlift-d2f8e.firebasestorage.app/o/uploads%2Fuser_profile%2Fdefault_user.png?alt=media&token=379f0844-dd73-44ec-9da1-58aa7948e2fc'),
        ),
    ]
