# Generated by Django 5.1.1 on 2024-11-26 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_check'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='calves',
            new_name='calf',
        ),
    ]
